config/routes.rb
Rails.application.routes.draw do
  resources :documents

end

app/models/document.rb
class Document < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:name, :description, :created_on, :tags)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :created_on %><br>
    <%= f.date_select :created_on %>
  </div>
  <div class="field">
    <%= f.label :tags %><br>
    <%= f.text_field :tags %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<h1>Listing documents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Created on</th>
      <th>Tags</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.name %></td>
        <td><%= document.description %></td>
        <td><%= document.created_on %></td>
        <td><%= document.tags %></td>
        <td><%= link_to 'Show', document %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<h1>New document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @document.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @document.description %>
</p>

<p>
  <strong>Created on:</strong>
  <%= @document.created_on %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @document.tags %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es_ES">
<head>
  <title>CulturArt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <!-- <?php echo $this->headMeta()
			->setCharset('utf8')
		    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
		    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
		?> -->
  
  <!-- Le styles -->
		<!-- <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
		                ->prependStylesheet($this->basePath() . '/css/style.css?v=1.0.0', 'screen')
		                ->prependStylesheet($this->basePath() . '/css/reset.css?v=1.0.0', 'screen')
		                ->prependStylesheet($this->basePath() . '/css/skeleton.css?v=1.0.0', 'screen')
		                ->prependStylesheet($this->basePath() . '/css/superfish.css?v=1.0.0', 'screen')
		                ->prependStylesheet($this->basePath() . '/css/flexslider.css?v=1.0.0', 'screen')
		                ->prependStylesheet($this->basePath() . '/css/forms.css?v=1.0.0', 'screen')
						->prependStylesheet($this->basePath() . '/css/map.css?v=1.0.0', 'screen')
						->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
						->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
		                ->prependStylesheet($this->basePath() . '/css/ie.css?v=1.0.0', 'all', 'IE 9') ?> -->
		
		<!-- Scripts -->
        <!-- <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/jquery-1.7.1.min.js')
            ->prependFile('https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false')
			->appendFile($this->basePath() . '/js/jquery-ui-1.10.3.custom.min.js')
            ->appendFile($this->basePath() . '/js/script.js?v=1.0.0')
            ->appendFile($this->basePath() . '/js/superfish.js?v=1.0.0')
            ->appendFile($this->basePath() . '/js/jquery.responsivemenu.js')
            ->appendFile($this->basePath() . '/js/jquery.flexslider-min.js')
            ->appendFile($this->basePath() . '/js/FF-cash.js?v=1.0.0')			
			->appendFile($this->basePath() . '/js/map.js?v=1.0.0')  
			->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->appendFile($this->basePath() . '/js/html5.js?v=1.0.0',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?> -->
				
		<!--[if lt IE 8]>
		   <div style=' clear: both; text-align:center; position: relative;'>
		     <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
		       <img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
		    </a>
		  </div>
		<![endif]-->
</head>
<body>
<!-- header -->
<header class="padheader">
	<div class="container_24">
		<div class="grid_24">
			<h1 class="fleft"><a href="<?php echo $this->url('home') ?>">CulturARt</a></h1>
			<ul class="sf-menu">
				<li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
				<li><a href="<?php echo $this->url('content') ?>">Maker</a><ul>
						<li><a href="#"><?php echo utf8_encode('Tipologías')?></a><ul>
								<li><a href="<?php echo $this->url('content', array(
								                	'controller' => 'morfologia', 
													'action' => 'index')) ?>">
										<?php echo utf8_encode('Morfología')?></a></li>
							</ul>
						</li>
					</ul>
				</li>
				<li><a href="#">El proyecto&nbsp;<span class="arrow"></span></a><ul>
						<li><a href="#">History</a></li>
						<li><a href="#">Work Team</a></li>
						<li><a href="#">Profile</a><ul>
								<li><a href="#">Mission</a></li>
								<li><a href="#">Capabilities</a></li>
								<li><a href="#">Support</a></li>
								<li><a href="#">Partnership</a></li>
							</ul>
						</li>
						<li><a href="#">Testimonials</a></li>
					</ul>
				</li>
				<li><a href="#">Contacto</a></li>
			</ul>
			<div class="clear"></div>
		</div>
		<div class="clear"></div>
	</div>
</header>
<!-- banner -->
<!-- <?php echo $this->layout()->slider ?> -->
<!-- content -->
<section>
	<%= yield %>
</section>
<!-- footer -->
<footer class="padfooter">
	<div class="container_24">
		<div class="wrapper">
			<div class="grid_24">
				<a href="<?php echo $this->url('home') ?>" class="link">
					<img src="<?php echo $this->basePath('images/logo-footer.png') ?>" alt="">
				</a> &copy; 2013 - <?php echo date('Y') ?> | <?php echo $this->translate('All rights reserved.') ?>
			</div>
		</div>
	</div>
</footer>

<!-- <?php echo $this->inlineScript() ?> -->
</body>
</html>